---
version: "3.7"

services:
  traefik:
    image: traefik:v2.5@sha256:3a861f1c6d23faf2f1618f28d3a342c99ba23baa754e3b76351f86837b565d1c
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL:-ERROR}"
      # letsencrypt configuration
      - "--certificatesResolvers.http.acme.email=${TRAEFIK_ACME_MAIL:-example@example.org}"
      - "--certificatesResolvers.http.acme.storage=/certs/acme.json"
      - "--certificatesResolvers.http.acme.httpChallenge.entryPoint=http"
      # enable dashboard
      - "--api.dashboard=true"
      # define entrypoints
      - "--entryPoints.http.address=:80"
      - "--entryPoints.http.http.redirections.entryPoint.to=https"
      - "--entryPoints.http.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.https.address=:443"
      # docker provider (get configuration from container labels)
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "certs:/certs"
    labels:
      - "traefik.enable=${TRAEFIK_DASHBOARD:-false}"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_BASIC_AUTH_USERS:-admin:$apr1$4vqie50r$YQAmQdtmz5n9rEALhxJ4l.}" # defaults to admin:admin
      - "traefik.http.routers.traefik.entrypoints=https"
      - "traefik.http.routers.traefik.rule=Host(`${TRAEFIK_DOMAIN:-traefik.owncloud.test}`)"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.routers.traefik.tls.certresolver=http"
      - "traefik.http.routers.traefik.service=api@internal"
    logging:
      driver: "local"
    restart: always

  influxdb:
    image: influxdb:2.1@sha256:6597ad58ab996d75e4f000e6295d2a2db8543644e329f009d0e3b7ceaaed3940
    volumes:
      - ./config/influxdb/provisioning/users.sh:/docker-entrypoint-initdb.d/users.sh
      - influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-superlongadminpassword}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN:-superlongadmintoken}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-k6-benchmark}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-k6-benchmark}
      #- DOCKER_INFLUXDB_INIT_RETENTION=
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.entrypoints=https"
      - "traefik.http.routers.influxdb.rule=Host(`${INFLUXDB_DOMAIN:-influxdb.owncloud.test}`)"
      - "traefik.http.routers.influxdb.tls.certresolver=http"
      - "traefik.http.routers.influxdb.service=influxdb"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"
    logging:
      driver: "local"
    restart: always

  grafana:
    image: grafana/grafana:8.3.2@sha256:e569f73afd968e1bd340d8fbc2fcd0d641807d0408c648cc99f429ec3720e582
    volumes:
      - grafana:/var/lib/grafana
      - ./config/grafana/dashboards/:/etc/grafana/dashboards/
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN:-grafana.owncloud.test}
      - GF_SERVER_ROOT_URL=https://${GRAFANA_DOMAIN:-grafana.owncloud.test}
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-github-datasource,grafana-clock-panel,natel-influx-admin-panel
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/home.json
      # influx data source
      - GRAFANA_INFLUXDB_ORG=${INFLUXDB_ORG:-k6-benchmark}
      - GRAFANA_INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-k6-benchmark}
      - GRAFANA_INFLUXDB_TOKEN=${GRAFANA_INFLUXDB_TOKEN:-superlongadmintoken}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN:-grafana.owncloud.test}`)"
      - "traefik.http.routers.grafana.tls.certresolver=http"
      - "traefik.http.routers.grafana.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    logging:
      driver: "local"
    restart: always

volumes:
  certs:
  influxdb:
  grafana:
