apiVersion: 1

# https://grafana.com/docs/grafana/latest/datasources/influxdb/provision-influxdb/

datasources:
  - name: K6-InfluxDB-Flux
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: $GRAFANA_INFLUXDB_TOKEN
    jsonData:
      version: Flux
      organization: $GRAFANA_INFLUXDB_ORG
      defaultBucket: $GRAFANA_INFLUXDB_BUCKET

  - name: K6-InfluxDB-InfluxQL
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    # This database needs to be mapped to a bucket
    # Get the ID of your bucket
    # influx bucket list
    # Create a mapping
    # influx v1 dbrp create --db k6-benchmark --default --rp infinity --bucket-id <bucket id>
    database: $GRAFANA_INFLUXDB_BUCKET
    jsonData:
      httpMode: GET
      httpHeaderName1: Authorization
    secureJsonData:
      httpHeaderValue1: Token $GRAFANA_INFLUXDB_TOKEN
