apiVersion: 1

datasources:
  - name: K6-InfluxDB
    type: influxdb
    access: proxy
    database: k6
    user: $INFLUXDB_GF_USERNAME
    url: http://influxdb:8086
    jsonData:
      httpMode: GET
    secureJsonData:
      password: $INFLUXDB_GF_PASSWORD
